language: python

sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  - PYTHONPATH=tests/testapp

before_install:
  - travis_retry pip install codecov

install:
  - travis_retry pip install -U -r dev-requirements.txt
  - travis_retry pip install -U .

before_script:
    - flake8 .

script: py.test

after_success:
  codecov
