language: python

sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  - PYTHONPATH=tests/testapp

install:
  - pip install -U -r dev-requirements.txt
  - pip install -U .

before_script:
    - flake8 .

script: py.test
