language: python

sudo: false

python:
- "2.7"
- "3.6"
- "pypy"

env:
  global:
  - PYTHONPATH=tests/testapp
  matrix:
  - DJANGO_VERSION=">=1.8,<1.9"
  - DJANGO_VERSION=">=1.9,<1.10"
  - DJANGO_VERSION=">=1.10,<1.11"
  - DJANGO_VERSION=">=1.11,<2.0"
  - DJANGO_VERSION="==2.0b1"

matrix:
  exclude:
  - python: "2.7"
    env: DJANGO_VERSION="==2.0b1"
  - python: "pypy"
    env: DJANGO_VERSION="==2.0b1"

before_install:
- travis_retry pip install codecov

install:
- travis_retry pip install -U -r dev-requirements.txt
- travis_retry pip install -U "django$DJANGO_VERSION"
- travis_retry pip install -U .

before_script:
- flake8 .

script: pytest

after_success:
  codecov
