language: python

sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  global:
    - PYTHONPATH=tests/testapp
  matrix:
    - DJANGO_VERSION=1.8.2
    - DJANGO_VERSION=1.7.8

before_install:
  - travis_retry pip install codecov

install:
  - travis_retry pip install -U -r dev-requirements.txt
  - travis_retry pip install -U django==$DJANGO_VERSION
  - travis_retry pip install -U .

before_script:
  - flake8 .

script: py.test

after_success:
  codecov
